name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Создание файла .env  
      run:  
        echo "PG_DATABASE=test" >> analyzer_service/.env  
        echo "PG_USER=user" >> analyzer_service/.env 
        echo "PG_PASSWORD=password" >> analyzer_service/.env  
        echo "PG_HOST=db" >> analyzer_service/.env 
        echo "PG_PORT=5432" >> analyzer_service/.env  
        echo "TOKEN=token" >> analyzer_service/.env 

    - name: Build the images and start the containers
      run: |
        export GITHUB_WORKFLOW=True
        export MODE="Test"
        docker compose  build
        docker compose  up -d
        # run: docker compose up -d --build
    - name: django
      run: |
        docker compose run --rm  api python manage.py makemigrations core
    - name: migrate
      run: |
        docker compose run --rm  api python manage.py migrate
    - name: test django
      run: |
        docker compose run --rm  api python manage.py test

    - name: Stop containers
      if: always()
      run: docker compose down
