name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Создание файла .env  
      run:  
        echo "PG_DATABASE=PG_DATABASE" >> analyzer_service/.env  
        echo "PG_USER=PG_USER" >> analyzer_service/.env 
        echo "PG_PASSWORD=PG_PASSWORD" >> analyzer_service/.env  
        echo "PG_HOST=PG_HOST" >> analyzer_service/.env 
        echo "PG_PORT=PG_PORT" >> analyzer_service/.env  
        echo "TOKEN=TOKEN" >> analyzer_service/.env 




 

    - name: Build the images and start the containers
      run: |
        export GITHUB_WORKFLOW=True
        export MODE="Test"
        docker compose  build
        docker compose  up -d
        # run: docker compose up -d --build
    - name: test django
      run: |
        docker compose exec api python manage.py test

    - name: Stop containers
      if: always()
      run: docker compose down
